Repository MinavKaria/Ratna-Supermarket, pull requests merged in 2024-10, with the labels that each got.

#37 added hover effect to footer to enhance user experience
  client/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#119 Fixed Vendor Page + Added Scrollbar when Overflow-y
  client/src/pages/Vendor.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#146 ✨added multi language support system✨
  client/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#169 Addeed the cursor animations solved #160
  client/src/App.jsx
  client/src/TrailingCursor.css
  client/src/TrailingCursor.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3
