Repository MinavKaria/Ratna-Supermarket, pull requests merged in 2024-11, with the labels that each got.

#183 Add feedback form
  client/package-lock.json
  client/package.json
  client/src/configs/route.jsx
  client/src/pages/WebsiteFeedback.jsx
  server/feedbackSchema.js
  server/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#187 Enhanced Design of the HomePage, Removed Corner Glitches, added new button to add product, etc
  client/package-lock.json
  client/package.json
  client/src/TrailingCursor.css
  client/src/components/BuyCard.jsx
  client/src/components/Carousel.jsx
  client/src/components/TopCategoriesList.jsx
  client/src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#177 Added MIT License
  LICENSE
Labels: gssoc-ext, hacktoberfest-accepted, level1

#191 Enhance CSS Styling for Footer and Cart Components
  client/src/components/Footer.jsx
  client/src/pages/Cart.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2
